// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: domain/addons_v1.proto

package domain

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Country int32

const (
	Country_UNDEFINED Country = 0
	Country_DE        Country = 1
	Country_US        Country = 2
)

// Enum value maps for Country.
var (
	Country_name = map[int32]string{
		0: "UNDEFINED",
		1: "DE",
		2: "US",
	}
	Country_value = map[string]int32{
		"UNDEFINED": 0,
		"DE":        1,
		"US":        2,
	}
)

func (x Country) Enum() *Country {
	p := new(Country)
	*p = x
	return p
}

func (x Country) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Country) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_addons_v1_proto_enumTypes[0].Descriptor()
}

func (Country) Type() protoreflect.EnumType {
	return &file_domain_addons_v1_proto_enumTypes[0]
}

func (x Country) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Country.Descriptor instead.
func (Country) EnumDescriptor() ([]byte, []int) {
	return file_domain_addons_v1_proto_rawDescGZIP(), []int{0}
}

type Language int32

const (
	Language_UNSPECIFIED Language = 0
	Language_de          Language = 1
	Language_en          Language = 2
	Language_fr          Language = 3
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "de",
		2: "en",
		3: "fr",
	}
	Language_value = map[string]int32{
		"UNSPECIFIED": 0,
		"de":          1,
		"en":          2,
		"fr":          3,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_addons_v1_proto_enumTypes[1].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_domain_addons_v1_proto_enumTypes[1]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_domain_addons_v1_proto_rawDescGZIP(), []int{1}
}

type Locale struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lang    Language `protobuf:"varint,1,opt,name=lang,proto3,enum=domain.Language" json:"lang,omitempty"`
	Country Country  `protobuf:"varint,2,opt,name=country,proto3,enum=domain.Country" json:"country,omitempty"`
}

func (x *Locale) Reset() {
	*x = Locale{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_addons_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Locale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Locale) ProtoMessage() {}

func (x *Locale) ProtoReflect() protoreflect.Message {
	mi := &file_domain_addons_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Locale.ProtoReflect.Descriptor instead.
func (*Locale) Descriptor() ([]byte, []int) {
	return file_domain_addons_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Locale) GetLang() Language {
	if x != nil {
		return x.Lang
	}
	return Language_UNSPECIFIED
}

func (x *Locale) GetCountry() Country {
	if x != nil {
		return x.Country
	}
	return Country_UNDEFINED
}

type YearWeek struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Year uint32 `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Week uint32 `protobuf:"varint,2,opt,name=week,proto3" json:"week,omitempty"`
}

func (x *YearWeek) Reset() {
	*x = YearWeek{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_addons_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YearWeek) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearWeek) ProtoMessage() {}

func (x *YearWeek) ProtoReflect() protoreflect.Message {
	mi := &file_domain_addons_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearWeek.ProtoReflect.Descriptor instead.
func (*YearWeek) Descriptor() ([]byte, []int) {
	return file_domain_addons_v1_proto_rawDescGZIP(), []int{1}
}

func (x *YearWeek) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *YearWeek) GetWeek() uint32 {
	if x != nil {
		return x.Week
	}
	return 0
}

type Section struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Handle      string `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Index       int32  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Singular    string `protobuf:"bytes,3,opt,name=singular,proto3" json:"singular,omitempty"`
	Plural      string `protobuf:"bytes,4,opt,name=plural,proto3" json:"plural,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ImageUri    string `protobuf:"bytes,6,opt,name=image_uri,json=imageUri,proto3" json:"image_uri,omitempty"`
}

func (x *Section) Reset() {
	*x = Section{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_addons_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_domain_addons_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_domain_addons_v1_proto_rawDescGZIP(), []int{2}
}

func (x *Section) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *Section) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Section) GetSingular() string {
	if x != nil {
		return x.Singular
	}
	return ""
}

func (x *Section) GetPlural() string {
	if x != nil {
		return x.Plural
	}
	return ""
}

func (x *Section) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Section) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

var File_domain_addons_v1_proto protoreflect.FileDescriptor

var file_domain_addons_v1_proto_rawDesc = []byte{
	0x0a, 0x16, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x61, 0x64, 0x64, 0x6f, 0x6e, 0x73, 0x5f,
	0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6d, 0x0a, 0x06, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x10, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x82, 0x01, 0x02, 0x10, 0x01, 0x52, 0x04, 0x6c,
	0x61, 0x6e, 0x67, 0x12, 0x33, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x82, 0x01, 0x02, 0x10, 0x01, 0x52,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x4a, 0x0a, 0x08, 0x59, 0x65, 0x61, 0x72,
	0x57, 0x65, 0x65, 0x6b, 0x12, 0x1f, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x42, 0x0b, 0xfa, 0x42, 0x08, 0x2a, 0x06, 0x10, 0xee, 0x0f, 0x28, 0xda, 0x0f, 0x52,
	0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x1d, 0x0a, 0x04, 0x77, 0x65, 0x65, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x2a, 0x04, 0x18, 0x34, 0x28, 0x01, 0x52, 0x04,
	0x77, 0x65, 0x65, 0x6b, 0x22, 0xaa, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x69, 0x6e, 0x67, 0x75, 0x6c, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x69, 0x6e, 0x67, 0x75, 0x6c, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c,
	0x75, 0x72, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x75, 0x72,
	0x61, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72,
	0x69, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72,
	0x69, 0x2a, 0x28, 0x0a, 0x07, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x0d, 0x0a, 0x09,
	0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x44,
	0x45, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x55, 0x53, 0x10, 0x02, 0x2a, 0x33, 0x0a, 0x08, 0x4c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x64, 0x65, 0x10, 0x01,
	0x12, 0x06, 0x0a, 0x02, 0x65, 0x6e, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x66, 0x72, 0x10, 0x03,
	0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69,
	0x67, 0x6f, 0x72, 0x2d, 0x74, 0x6f, 0x6e, 0x6b, 0x6f, 0x70, 0x72, 0x79, 0x61, 0x64, 0x63, 0x68,
	0x65, 0x6e, 0x6b, 0x6f, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_domain_addons_v1_proto_rawDescOnce sync.Once
	file_domain_addons_v1_proto_rawDescData = file_domain_addons_v1_proto_rawDesc
)

func file_domain_addons_v1_proto_rawDescGZIP() []byte {
	file_domain_addons_v1_proto_rawDescOnce.Do(func() {
		file_domain_addons_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_domain_addons_v1_proto_rawDescData)
	})
	return file_domain_addons_v1_proto_rawDescData
}

var file_domain_addons_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_domain_addons_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_domain_addons_v1_proto_goTypes = []interface{}{
	(Country)(0),     // 0: domain.Country
	(Language)(0),    // 1: domain.Language
	(*Locale)(nil),   // 2: domain.Locale
	(*YearWeek)(nil), // 3: domain.YearWeek
	(*Section)(nil),  // 4: domain.Section
}
var file_domain_addons_v1_proto_depIdxs = []int32{
	1, // 0: domain.Locale.lang:type_name -> domain.Language
	0, // 1: domain.Locale.country:type_name -> domain.Country
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_domain_addons_v1_proto_init() }
func file_domain_addons_v1_proto_init() {
	if File_domain_addons_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_domain_addons_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Locale); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_addons_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YearWeek); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_addons_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Section); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_domain_addons_v1_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_addons_v1_proto_goTypes,
		DependencyIndexes: file_domain_addons_v1_proto_depIdxs,
		EnumInfos:         file_domain_addons_v1_proto_enumTypes,
		MessageInfos:      file_domain_addons_v1_proto_msgTypes,
	}.Build()
	File_domain_addons_v1_proto = out.File
	file_domain_addons_v1_proto_rawDesc = nil
	file_domain_addons_v1_proto_goTypes = nil
	file_domain_addons_v1_proto_depIdxs = nil
}
